/**
 * GOD-SWARM ULTRA — Code Generation Agent
 * Writes production-grade software from natural language descriptions
 */

import type { AgentExecutionContext } from './base.js';
import type { TaskOutput, Artifact } from '../swarm/types.js';
import { BaseAgent } from './base.js';

export interface CodeGenRequest {
  description: string;
  language?: string;
  framework?: string;
  requirements?: string[];
  existingCode?: string;
}

export interface CodeGenResult {
  files: Array<{ path: string; content: string; language: string }>;
  explanation: string;
  testSuite?: string;
}

export class CodeGenAgent extends BaseAgent {
  constructor() {
    super('code-gen', 'Code Generation Agent', {
      tools: ['file-write', 'file-read', 'git-commit', 'test-runner', 'linter', 'formatter'],
      models: ['gpt-4o', 'claude-3-5-sonnet-20241022', 'o1-mini'],
      maxConcurrentTasks: 2,
      supportedLanguages: ['TypeScript', 'JavaScript', 'Python', 'Rust', 'Go', 'Solidity'],
    });
  }

  async execute(context: AgentExecutionContext): Promise<TaskOutput> {
    this.setStatus('running');
    const logs: string[] = [];

    try {
      const prompt = context.task.input.prompt ?? context.task.description;
      logs.push(`[CodeGenAgent] Generating code for: ${prompt}`);

      // Parse language and framework from context
      const taskContext = context.task.input.context ?? {};
      const language = (taskContext['language'] as string) ?? 'TypeScript';
      const framework = (taskContext['framework'] as string) ?? '';

      logs.push(`[CodeGenAgent] Target: ${language}${framework ? ` / ${framework}` : ''}`);

      // In a real implementation, this would call an LLM via the model router
      // Here we generate a framework-level skeleton
      const result = this.generateCodeSkeleton(prompt, language, framework);

      const artifacts: Artifact[] = result.files.map(f => ({
        id: `code-${Date.now()}-${f.path.replace(/\//g, '-')}`,
        type: 'code',
        name: f.path,
        content: f.content,
        mimeType: this.getMimeType(f.language),
      }));

      logs.push(`[CodeGenAgent] Generated ${result.files.length} files`);
      result.files.forEach(f => logs.push(`  → ${f.path}`));

      this.setStatus('idle');
      return {
        result,
        artifacts,
        logs,
        metrics: { startTime: new Date(), endTime: new Date() },
      };
    } catch (err) {
      this.setStatus('error');
      return {
        error: err instanceof Error ? err.message : String(err),
        logs,
        metrics: { startTime: new Date(), endTime: new Date() },
      };
    }
  }

  private generateCodeSkeleton(
    description: string,
    language: string,
    framework: string
  ): CodeGenResult {
    const lang = language.toLowerCase();

    if (lang === 'typescript' || lang === 'javascript') {
      return this.generateTypeScriptSkeleton(description, framework);
    } else if (lang === 'python') {
      return this.generatePythonSkeleton(description);
    } else if (lang === 'solidity') {
      return this.generateSoliditySkeleton(description);
    }

    return {
      files: [
        {
          path: `src/main.${lang.slice(0, 2)}`,
          content: `// Generated by GOD-SWARM ULTRA CodeGen Agent\n// Task: ${description}\n// TODO: Implement\n`,
          language,
        },
      ],
      explanation: `Generated ${language} skeleton for: ${description}`,
    };
  }

  private generateTypeScriptSkeleton(description: string, framework: string): CodeGenResult {
    const content = `/**
 * Generated by GOD-SWARM ULTRA — Code Generation Agent
 * Task: ${description}
 */

export interface Config {
  // Add configuration fields
}

export class Implementation {
  constructor(private config: Partial<Config> = {}) {}

  async execute(): Promise<void> {
    // TODO: Implement: ${description}
    throw new Error('Not implemented');
  }
}

export default Implementation;
`;

    const testContent = `import { describe, it, expect } from 'vitest';
import Implementation from '../src/implementation.js';

describe('Implementation', () => {
  it('should instantiate', () => {
    const impl = new Implementation();
    expect(impl).toBeDefined();
  });
});
`;

    return {
      files: [
        { path: 'src/implementation.ts', content, language: 'TypeScript' },
        { path: 'tests/implementation.test.ts', content: testContent, language: 'TypeScript' },
      ],
      explanation: `Generated TypeScript${framework ? ` (${framework})` : ''} implementation skeleton`,
      testSuite: testContent,
    };
  }

  private generatePythonSkeleton(description: string): CodeGenResult {
    const content = `"""
Generated by GOD-SWARM ULTRA — Code Generation Agent
Task: ${description}
"""

from dataclasses import dataclass
from typing import Optional


@dataclass
class Config:
    # Add configuration fields
    pass


class Implementation:
    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()

    async def execute(self) -> None:
        """${description}"""
        raise NotImplementedError("TODO: Implement")
`;

    return {
      files: [{ path: 'src/implementation.py', content, language: 'Python' }],
      explanation: 'Generated Python implementation skeleton',
    };
  }

  private generateSoliditySkeleton(description: string): CodeGenResult {
    const content = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title GeneratedContract
 * @dev Generated by GOD-SWARM ULTRA — Code Generation Agent
 * @notice ${description}
 */
contract GeneratedContract {
    address public owner;

    event ActionExecuted(address indexed by, uint256 timestamp);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    function execute() external onlyOwner {
        // TODO: Implement: ${description}
        emit ActionExecuted(msg.sender, block.timestamp);
    }
}
`;

    return {
      files: [{ path: 'contracts/GeneratedContract.sol', content, language: 'Solidity' }],
      explanation: 'Generated Solidity contract skeleton',
    };
  }

  private getMimeType(language: string): string {
    const map: Record<string, string> = {
      TypeScript: 'application/typescript',
      JavaScript: 'application/javascript',
      Python: 'text/x-python',
      Solidity: 'text/x-solidity',
      Rust: 'text/x-rust',
      Go: 'text/x-go',
    };
    return map[language] ?? 'text/plain';
  }
}
