/**
 * GOD-SWARM ULTRA — Research Agent
 * Collects and synthesizes information from external sources
 */

import type { AgentExecutionContext } from './base.js';
import type { TaskOutput, Artifact } from '../swarm/types.js';
import { BaseAgent } from './base.js';

export interface ResearchQuery {
  topic: string;
  sources?: string[];
  depth?: 'shallow' | 'moderate' | 'deep';
  outputFormat?: 'summary' | 'detailed' | 'structured';
}

export interface ResearchResult {
  topic: string;
  summary: string;
  keyFindings: string[];
  sources: Array<{ title: string; url?: string; excerpt?: string }>;
  confidence: number;
  timestamp: Date;
}

export class ResearchAgent extends BaseAgent {
  constructor() {
    super('research', 'Research Agent', {
      tools: [
        'web-search',
        'web-scraper',
        'pdf-extractor',
        'api-connector',
        'github-api',
        'arxiv-api',
      ],
      models: ['gpt-4o', 'claude-3-5-sonnet-20241022'],
      maxConcurrentTasks: 4,
    });
  }

  async execute(context: AgentExecutionContext): Promise<TaskOutput> {
    this.setStatus('running');
    const logs: string[] = [];

    try {
      const prompt = context.task.input.prompt ?? context.task.description;
      logs.push(`[ResearchAgent] Researching: ${prompt}`);

      const taskCtx = context.task.input.context ?? {};
      const depth = (taskCtx['depth'] as string) ?? 'moderate';
      const outputFormat = (taskCtx['outputFormat'] as string) ?? 'detailed';

      logs.push(`[ResearchAgent] Depth: ${depth}, Format: ${outputFormat}`);

      // In a real implementation, this would query external APIs and LLMs
      const result = this.synthesizeResearch(prompt, depth as ResearchQuery['depth']);

      logs.push(`[ResearchAgent] Found ${result.keyFindings.length} key findings`);
      logs.push(`[ResearchAgent] Confidence: ${(result.confidence * 100).toFixed(0)}%`);

      const report = this.generateReport(result, outputFormat as ResearchQuery['outputFormat']);

      const artifacts: Artifact[] = [
        {
          id: `research-${Date.now()}`,
          type: 'report',
          name: `research-${prompt.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}.md`,
          content: report,
          mimeType: 'text/markdown',
        },
      ];

      this.setStatus('idle');
      return {
        result,
        artifacts,
        logs,
        metrics: { startTime: new Date(), endTime: new Date() },
      };
    } catch (err) {
      this.setStatus('error');
      return {
        error: err instanceof Error ? err.message : String(err),
        logs,
        metrics: { startTime: new Date(), endTime: new Date() },
      };
    }
  }

  private synthesizeResearch(topic: string, depth?: ResearchQuery['depth']): ResearchResult {
    const depthMultiplier = depth === 'deep' ? 5 : depth === 'moderate' ? 3 : 1;

    return {
      topic,
      summary: `Research summary for: ${topic}. This analysis covers key aspects, current state, and future outlook.`,
      keyFindings: Array.from({ length: depthMultiplier }, (_, i) => [
        `Finding ${i + 1}: Core concept related to "${topic}"`,
        `Finding ${i + 1}b: Implementation consideration for "${topic}"`,
      ]).flat(),
      sources: [
        {
          title: 'Academic Research Papers',
          url: 'https://arxiv.org',
          excerpt: `Recent papers on ${topic}`,
        },
        { title: 'Industry Documentation', excerpt: `Best practices for ${topic}` },
        {
          title: 'Open Source Projects',
          url: 'https://github.com',
          excerpt: 'Reference implementations',
        },
      ],
      confidence: 0.75,
      timestamp: new Date(),
    };
  }

  private generateReport(result: ResearchResult, format?: ResearchQuery['outputFormat']): string {
    if (format === 'summary') {
      return `# Research Summary: ${result.topic}\n\n${result.summary}\n\n**Confidence**: ${(result.confidence * 100).toFixed(0)}%`;
    }

    return `# Research Report: ${result.topic}
Generated: ${result.timestamp.toISOString()}

## Summary
${result.summary}

## Key Findings
${result.keyFindings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

## Sources
${result.sources
  .map(
    s => `- **${s.title}**${s.url ? ` — [Link](${s.url})` : ''}
  ${s.excerpt ?? ''}`
  )
  .join('\n')}

## Confidence Assessment
**Confidence**: ${(result.confidence * 100).toFixed(0)}%

---
*Generated by GOD-SWARM ULTRA Research Agent v1.0.0*
`;
  }
}
